name: .NET

on: #my trigger events
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: #manually trigger the workflow
  
env: 
  WORKING_DIRECTORY: briceson-roy/P1

jobs:
  build:
    #Select which OS our VM's or runners to be
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3 #provides the runner with the source code
    - name: Setup .NET #we are downloading and installing .NET SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore ${{env.WORKING_DIRECTORY}}/RestaurantAPI
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
docker-image-build:
    runs-on: unbuntu-laters 
    
    steps:
    -uses: actions/checkout@v3
    
    -name: Docker Setup Buildx
  # You may pin to the exact commit or the version.
  # uses: docker/setup-buildx-action@dc7b9719a96d48369863986a06765841d7ea23f6
    uses: docker/setup-buildx-action@v2.0.0
    with:
    # Buildx version. (eg. v0.3.0)
      version: # optional
    # Sets the builder driver to be used
      driver: # optional, default is docker-container
    # List of additional driver-specific options. (eg. image=moby/buildkit:master)
      driver-opts: # optional
    # Flags for buildkitd daemon
      buildkitd-flags: # optional, default is --allow-insecure-entitlement security.insecure --allow-insecure-entitlement network.host
    # Sets up docker build command as an alias to docker buildx
      install: # optional, default is false
    # Switch to this builder instance
      use: # optional, default is true
    # Optional address for docker socket or context from `docker context ls`
      endpoint: # optional
    # BuildKit config file
      config: # optional
    # Inline BuildKit config
      config-inline: # optional
